In [2]:
!nvidia-smi

Tue Jun  9 19:32:10 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   33C    P0             56W /  400W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
## https://github.com/Dao-AILab/flash-attention/issues/2425
!pip install -qqq accelerate bitsandbytes peft
!pip install -qqq "https://github.com/lesj0610/flash-attention/releases/download/v2.8.3-cu12-torch2.11/flash_attn-2.8.3%2Bcu12torch2.11cxx11abiTRUE-cp312-cp312-linux_x86_64.whl"
!pip install -qqq --upgrade torchao

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 43.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.7/253.7 MB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 104.7 MB/s eta 0:00:00

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!cp -r /content/drive/MyDrive/eden/Indiana-CXR-Eden/eval\
    /content/drive/MyDrive/eden/Indiana-CXR-Eden/train\
    /content/drive/MyDrive/eden/Indiana-CXR-Eden/utils\
    /content/

In [15]:
!ls images/images_normalized/ | wc -l

4950

## intermediate steps

In [ ]:
# #!/bin/bash
# !curl -L -o /content/drive/MyDrive/eden/chest-xrays-indiana-university.zip\
#   https://www.kaggle.com/api/v1/datasets/download/raddar/chest-xrays-indiana-university

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13.1G  100 13.1G    0     0  58.8M      0  0:03:49  0:03:49 --:--:-- 61.8M

In [ ]:
# !unzip /content/drive/MyDrive/eden/chest-xrays-indiana-university.zip -d /content/drive/MyDrive/eden/

In [7]:
import pandas as pd

train = pd.read_csv("/content/drive/MyDrive/eden/Indiana-CXR-Eden/intermediate/train_v2.csv")
test = pd.read_csv("/content/drive/MyDrive/eden/Indiana-CXR-Eden/intermediate/test.csv")

In [6]:
train.loc[0, 'Frontal']

'../archive/images/images_normalized/1_IM-0001-4001.dcm.png'

In [7]:
test.loc[0, 'Frontal']

'../archive/images/images_normalized/25_IM-1024-2001.dcm.png'

In [8]:
replace_path = lambda x : x.replace("../archive/images/images_normalized",
        "/content/images/images_normalized") if isinstance(x, str) else None

In [9]:
train['Frontal'] = train['Frontal'].map(replace_path)
train['Lateral'] = train['Lateral'].map(replace_path)
test['Frontal'] = test['Frontal'].map(replace_path)
test['Lateral'] = test['Lateral'].map(replace_path)

In [10]:
train.to_csv("train.csv")
test.to_csv("test.csv")

In [11]:
import sys
sys.path.append("./Indiana-CXR-Eden/")

In [12]:
from utils import XRayReportDataset
train_df = XRayReportDataset(csv_file="train.csv")

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so

In [13]:
train_df[0]

{'messages': [{'role': 'user',
   'content': [{'type': 'image',
     'image': <PIL.Image.Image image mode=RGB size=768x768>},
    {'type': 'image', 'image': <PIL.Image.Image image mode=RGB size=768x768>},
    {'type': 'text',
     'text': 'Given the indication:\n\nINDICATION : Positive TB test\n\nPerform a systematic review of this chest X-ray against the following clinical categories:\n1. Cardiomegaly & Cardiovascular\n2. Alveolar Opacities & Infections\n3. Pleural Space Diseases\n4. COPD & Hyperinflation\n5. Atelectasis & Volume Loss\n6. Nodules, Masses & Fibrosis\n7. Bones & Spine\n8. Medical Devices\n9. Diaphragm & Extrathoracic\n\nBased on this systematic review, generate the findings and impression in the xml format as specified below.\n\noutput format:\n\n<findings> Findings </findings>\n<impression> Impression </impression>\n'}]},
  {'role': 'assistant',
   'content': [{'type': 'text',
     'text': '<findings> The cardiac silhouette and mediastinum size are within normal limits. There is no pulmonary edema. There is no focal consolidation. There are no XXXX of a pleural effusion. There is no evidence of pneumothorax. </findings>\n<impression> Normal chest x-XXXX. </impression>'}]}],
 'images': [<PIL.Image.Image image mode=RGB size=768x768>,
  <PIL.Image.Image image mode=RGB size=768x768>]}

## preprocessing

In [16]:
from utils.resize_and_save_images import main

In [17]:
main(INPUT_CSV="test.csv", OUTPUT_CSV="test_resized.csv")

Reading test.csv...
Processing 369 images using all CPU cores...

100%|██████████| 369/369 [00:06<00:00, 58.47it/s]

Done! Resized images saved to: resized_images/
Updated CSV saved to: test_resized.csv

In [18]:
main(INPUT_CSV="train.csv", OUTPUT_CSV="train_resized.csv")

Reading train.csv...
Processing 14032 images using all CPU cores...

100%|██████████| 14032/14032 [03:58<00:00, 58.81it/s]

Done! Resized images saved to: resized_images/
Updated CSV saved to: train_resized.csv

## training

In [1]:
from train.train import main

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so

In [3]:
main(
    train_name = "clahe",
    model_mode="encoder-decoder",
     output_dir_root="/content/drive/MyDrive/eden/Indiana-CXR-Eden/checkpoints",
     train_csv_path="train_resized.csv",
     test_csv_path = "test_resized.csv")

Loading base model: Qwen/Qwen3-VL-2B-Instruct...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 24,641,536 || all params: 2,152,173,568 || trainable%: 1.1450
Loading Training Dataset...
Loading Testing/Validation Dataset...
Train size: 7517 | Eval size: 198
Starting training...

[transformers] `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

KeyboardInterrupt:

In [1]:
from eval.generate_response import generate_reports

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so

In [2]:
generate_reports(
    LORA_ADAPTER_PATH = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/checkpoints/qwen-vl-report-lora-encoder-decoder-frontal_and_lateral-clahe/checkpoint-1000",
    TEST_CSV = "test_resized.csv" ,
    OUTPUT_CSV = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/evaluation_results_encoder_decoder_augment_oversampled_clahe.csv")

print("Output file generated!!")

Loading test dataset: test_resized.csv
Loading base model: Qwen/Qwen3-VL-2B-Instruct...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]

Loading LoRA weights from: /content/drive/MyDrive/eden/Indiana-CXR-Eden/checkpoints/qwen-vl-report-lora-encoder-decoder-frontal_and_lateral-clahe/checkpoint-1000...
Model merged and ready for generation.

Generating Reports (BS=8):   0%|          | 0/25 [00:00<?, ?it/s][transformers] The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Generating Reports (BS=8): 100%|██████████| 25/25 [03:41<00:00,  8.88s/it]

Finished! Results saved to /content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/evaluation_results_encoder_decoder_augment_oversampled_clahe.csv
Output file generated!!

In [3]:
import pandas as pd
import os


# root = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/"
# name = "evaluation_results_encoder_decoder_augment_oversampled.csv"
OUTPUT_CSV = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/evaluation_results_encoder_decoder_augment_oversampled_clahe.csv"

# df = pd.read_csv(os.path.join(root, name))
df = pd.read_csv(OUTPUT_CSV)

In [5]:
row = df.loc[110]
print(f"<findings> {row['findings']} </findings>\n\n<impression> {row['impression']} </impression>")
print("\n\n----xxxx----\n\n")
print(f"{row['generated_report']}")

<findings> Mild hypoventilation with bronchovascular crowding and prominent central and basilar interstitial markings. No focal alveolar consolidation, no pleural effusion demonstrated. Considering technical factors heart size XXXX within normal limits. </findings>

<impression> Prominent interstitial markings in the central lungs and bases which may be secondary to low lung volumes with bronchovascular crowding, differential considerations include interstitial infiltrates of inflammatory or infectious etiology and mild pulmonary edema. Clinical correlation is recommended. </impression>


----xxxx----


<findings> There are scattered calcified granulomas. The cardiomediastinal silhouette is within normal limits for appearance. No pneumothorax or pleural effusions. Minimal right base subsegmental atelectasis versus scarring. </findings>
<impression> 1. Probable minimal right lower lobe airspace disease process versus chronic change. 2. Otherwise clear lungs. </impression>

## evaluation

In [ ]:
!pip install radgraph --no-cache-dir

In [2]:
from radgraph import F1RadGraph
refs = ["no acute cardiopulmonary abnormality",
        "endotracheal tube is present and bibasilar opacities likely represent mild atelectasis",
]

hyps = ["no acute cardiopulmonary abnormality",
        "et tube terminates 2 cm above the carina and bibasilar opacities"
]
f1radgraph = F1RadGraph(reward_level="all", model_type="radgraph-xl")
mean_reward, reward_list, hypothesis_annotation_lists, reference_annotation_lists = f1radgraph(hyps=hyps, refs=refs)

rg_e, rg_er, rg_bar_er = mean_reward

print(mean_reward)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

Using device: cuda:0

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

(np.float64(0.75), np.float64(0.6666666666666666), np.float64(0.6538461538461539))

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# pip install green-score --ignore-requires-python
# !pip install peft==0.14.0
# !pip install --upgrade transformers peft diffusers accelerate
# !pip install --upgrade torch torchvision torchaudio

In [1]:
# 1. Configuration
# ==========================================
CSV_FILE = "evaluation_results.csv"

# For BERTScore, using a medical-specific BERT model yields much more accurate clinical similarity
BERTSCORE_MODEL = "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"

# For GREEN, Stanford provides a fine-tuned 7B model
GREEN_MODEL_ID = "StanfordAIMI/GREEN-radllama2-7b"

In [ ]:
# pip install crimson-score

In [1]:
import os

os.environ['OPENAI_API_KEY'] = "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"

In [8]:
from CRIMSON import CRIMSONScore
import numpy as np
from tqdm import tqdm

def clean_text(text):
    """Handles NaNs and strips whitespace"""
    if pd.isna(text) or str(text).lower() == "nan":
        return ""
    return str(text).strip()

def compute_bertscore(hypotheses, references):
    """Computes BERTScore using a specified medical BERT model."""
    print("\n[1/3] Computing BERTScore (using PubMedBERT)...")

    # P = Precision, R = Recall, F1 = F1 Score
    P, R, F1_bert = bert_score_fn(
        hypotheses,
        references,
        lang="en",
        model_type=BERTSCORE_MODEL,
        num_layers=12,
        use_fast_tokenizer=False,
        device="cuda" if torch.cuda.is_available() else "cpu",
    )
    bert_f1_mean = F1_bert.mean().item()
    print(f"-> BERTScore F1: {bert_f1_mean:.4f}")

    # Return the individual scores as a numpy array and the overall mean
    return F1_bert.numpy(), bert_f1_mean


def compute_radgraph(hypotheses, references):
    """Computes RadGraph F1 score."""
    print("\n[2/3] Computing RadGraph...")

    # reward_level="partial" gives credit for overlapping entities/relations
    radgraph_scorer = F1RadGraph(reward_level="partial")

    # RadGraph returns the mean score, list of scores, and the generated graphs
    rg_mean_score, rg_score_list, _, _ = radgraph_scorer(
        hyps=hypotheses, refs=references
    )
    print(f"-> RadGraph F1: {rg_mean_score:.4f}")

    return rg_score_list, rg_mean_score


def compute_green(hypotheses, references):
    """Computes GREEN score using the Stanford AIMI model."""
    print(f"\n[3/3] Computing GREEN (loading {GREEN_MODEL_ID})...")

    # GREEN loads a 7B parameter Llama-2 model internally onto your GPU
    green_scorer = GREEN(
        model_id_or_path=GREEN_MODEL_ID,
        device="cuda" if torch.cuda.is_available() else "cpu",
    )

    green_mean, green_std, green_score_list = green_scorer(
        refs=references, hyps=hypotheses
    )
    print(f"-> GREEN Score: {green_mean:.4f} ± {green_std:.4f}")

    return green_score_list, green_mean

def compute_crimson(hypotheses, references):
    """
    Computes CRIMSON scores for a list of report pairs.

    Returns:
        crimson_scores: list[float]
        crimson_mean: float
    """

    print("\n[4/4] Computing CRIMSON...")

    scorer = CRIMSONScore()  # Uses MedGemmaCRIMSON by default

    crimson_scores = []

    for ref, hyp in tqdm(
        zip(references, hypotheses),
        total=len(references),
        desc="CRIMSON",
    ):
        try:
            result = scorer.evaluate(
                reference_findings=ref,
                predicted_findings=hyp,
            )

            crimson_scores.append(result["crimson_score"])

        except Exception as e:
            print(f"CRIMSON failed: {e}")
            crimson_scores.append(np.nan)

    crimson_mean = np.nanmean(crimson_scores)

    print(f"-> CRIMSON Score: {crimson_mean:.4f}")

    return crimson_scores, crimson_mean

In [4]:
from CRIMSON import CRIMSONScore

# Default: uses the HuggingFace MedGemmaCRIMSON model
scorer = CRIMSONScore()
result = scorer.evaluate(
    reference_findings="Cardiomegaly. Small bilateral pleural effusions.",
    predicted_findings="Normal heart size. Small left pleural effusion.",
)

print(f"CRIMSON Score: {result['crimson_score']:.2f}")
print(f"False findings: {result['error_counts']['false_findings']}")
print(f"Missing findings: {result['error_counts']['missing_findings']}")
print(f"Attribute errors: {result['error_counts']['attribute_errors']}")

W0608 19:45:43.904000 40754 torch/utils/_pytree.py:630] <enum 'KernelPreference'> is an Enum subclass and is now natively supported by torch.compile as an opaque value type. Calling register_constant() on Enum subclasses is deprecated and will be an error in a future release.
W0608 19:45:43.937000 40754 torch/utils/_pytree.py:630] <enum 'ScaleCalculationMode'> is an Enum subclass and is now natively supported by torch.compile as an opaque value type. Calling register_constant() on Enum subclasses is deprecated and will be an error in a future release.

Loading HuggingFace model: rajpurkarlab/medgemma-4b-it-crimson

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.91k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/7.76G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/444 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/233 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/715 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

Model loaded.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GemmaTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

CRIMSON Score: 0.25
False findings: 0
Missing findings: 1
Attribute errors: 1

In [5]:
# ==========================================
# Main Execution
# ==========================================
from CRIMSON import CRIMSONScore

def main(CSV_FILE, output_name):
    print(f"Loading data from {CSV_FILE}...")
    df = pd.read_csv(CSV_FILE)

    references = []
    hypotheses = []

    # Combine Findings and Impression for full report evaluation
    for _, row in df.iterrows():
        # Ground Truth
        ref_f = clean_text(row.get("findings", ""))
        ref_i = clean_text(row.get("impression", ""))
        ref_full = f"{ref_f} {ref_i}".strip()

        # Model Generated
        hyp_f = clean_text(row.get("generated_findings", ""))
        hyp_i = clean_text(row.get("generated_impression", ""))
        hyp_full = f"{hyp_f} {hyp_i}".strip()

        # Fallback for empty strings to prevent metric crashes
        if not ref_full:
            ref_full = "normal study"
        if not hyp_full:
            hyp_full = "normal study"

        references.append(ref_full)
        hypotheses.append(hyp_full)

    print(f"\nLoaded {len(references)} report pairs for evaluation.")

    # Call the separated metric functions
    # bert_scores, bert_f1_mean = compute_bertscore(hypotheses, references)
    # rg_scores, rg_mean_score = compute_radgraph(hypotheses, references)
    # green_scores, green_mean = compute_green(hypotheses, references)
    crimson_scores, crimson_mean = compute_crimson(
        hypotheses,
        references,
    )

    # ==========================================
    # Save Results Back to CSV
    # ==========================================
    print("\nSaving granular metrics back to CSV...")
    # df["bertscore_f1"] = bert_scores
    # df["radgraph_f1"] = rg_scores
    df["crimson_scores"] = crimson_scores
    df["crimson_mean"] = crimson_mean
    root = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/"
    df.to_csv(os.path.join(root, output_name), index=False)
    print(f"Done! Final evaluation saved to: {output_name}")

    # Print Final Summary
    print("\n" + "=" * 40)
    print("        FINAL EVALUATION SUMMARY        ")
    print("=" * 40)
    # print(f"BERTScore F1 : {bert_f1_mean:.4f}")
    # print(f"RadGraph F1  : {rg_mean_score:.4f}")
    # print(f"GREEN Score  : {green_mean:.4f}")
    print(f"crimson Score  : {crimson_mean:.4f}")
    print("=" * 40)

In [9]:
import pandas as pd

root = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/"
name = "/content/drive/MyDrive/eden/evaluation_results_final_with_sampling_no_sys.csv"

CSV_FILE = os.path.join(root, name)
output_name = "evaluation_results_final_radgraph.csv"
main(CSV_FILE, output_name)

Loading data from /content/drive/MyDrive/eden/evaluation_results_final_with_sampling_no_sys.csv...

Loaded 198 report pairs for evaluation.

[4/4] Computing CRIMSON...
Loading HuggingFace model: rajpurkarlab/medgemma-4b-it-crimson

Loading weights:   0%|          | 0/444 [00:00<?, ?it/s]

Model loaded.

CRIMSON:   5%|▌         | 10/198 [01:47<39:22, 12.57s/it][transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
CRIMSON:  27%|██▋       | 54/198 [19:17<7:31:12, 188.00s/it]

CRIMSON failed: Failed to parse model response as JSON
Response (31275 chars):

CRIMSON: 100%|██████████| 198/198 [44:11<00:00, 13.39s/it]

-> CRIMSON Score: 0.1725

Saving granular metrics back to CSV...
Done! Final evaluation saved to: evaluation_results_final_radgraph.csv

========================================
        FINAL EVALUATION SUMMARY
========================================
crimson Score  : 0.1725
========================================

In [11]:
root = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/"
name = "/content/drive/MyDrive/eden/evaluation_results_final.csv"

CSV_FILE = os.path.join(root, name)
output_name = "evaluation_results_final_radgraph_1.csv"
main(CSV_FILE, output_name)

Loading data from /content/drive/MyDrive/eden/evaluation_results_final.csv...

Loaded 198 report pairs for evaluation.

[4/4] Computing CRIMSON...
Loading HuggingFace model: rajpurkarlab/medgemma-4b-it-crimson

Loading weights:   0%|          | 0/444 [00:00<?, ?it/s]

Model loaded.

CRIMSON:  47%|████▋     | 93/198 [22:51<5:24:23, 185.37s/it]

CRIMSON failed: Failed to parse model response as JSON
Response (29086 chars):

CRIMSON: 100%|██████████| 198/198 [37:47<00:00, 11.45s/it]

-> CRIMSON Score: 0.3949

Saving granular metrics back to CSV...
Done! Final evaluation saved to: evaluation_results_final_radgraph_1.csv

========================================
        FINAL EVALUATION SUMMARY
========================================
crimson Score  : 0.3949
========================================

In [10]:
root = "/content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/"
name = "evaluation_results_encoder_decoder_augment_oversampled_radgraph.csv"

CSV_FILE = os.path.join(root, name)
output_name = "evaluation_results_final_radgraph_2.csv"
main(CSV_FILE, output_name)

Loading data from /content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/evaluation_results_encoder_decoder_augment_oversampled_radgraph.csv...

Loaded 198 report pairs for evaluation.

[4/4] Computing CRIMSON...
Loading HuggingFace model: rajpurkarlab/medgemma-4b-it-crimson

Loading weights:   0%|          | 0/444 [00:00<?, ?it/s]

Model loaded.

CRIMSON:  45%|████▌     | 90/198 [29:37<5:33:18, 185.17s/it]

CRIMSON failed: Failed to parse model response as JSON
Response (33625 chars):

CRIMSON: 100%|██████████| 198/198 [53:43<00:00, 16.28s/it]

-> CRIMSON Score: 0.4921

Saving granular metrics back to CSV...
Done! Final evaluation saved to: evaluation_results_final_radgraph_2.csv

========================================
        FINAL EVALUATION SUMMARY
========================================
crimson Score  : 0.4921
========================================

In [ ]:
# !pip install bert-score

In [16]:
# cp -r /content/evaluation_results_encoder_decoder_augment_oversampled_radgraph.csv /content/drive/MyDrive/eden/Indiana-CXR-Eden/outputs/

In [2]:
import pandas as pd

df = pd.read_csv("/content/evaluation_results_encoder_decoder_augment_oversampled_radgraph.csv")

In [3]:
df

,Unnamed: 0,uid,MeSH,Problems,image,indication,comparison,findings,impression,buckets,Frontal,Lateral,generated_report,generated_findings,generated_impression,radgraph_f1
0,0,25,"Sutures/lung/apex/right;Lung, Hyperlucent;Lung...","Sutures;Lung, Hyperlucent;Lung;Pulmonary Emphy...",Xray Chest PA and Lateral,XXXX year old smoking on oxygen and nasal cann...,PA and lateral chest XXXX and CTA XXXX.,The heart is within normal limits in size. Sur...,1. Left lower lobe airspace disease and bilate...,Devices_Surgical_Support;Pleural_Space_Pneumot...,resized_images/row_0_frontal.jpg,resized_images/row_0_lateral.jpg,<findings> There is mild cardiomegaly. No foca...,There is mild cardiomegaly. No focal airspace ...,XXXX change. No acute pulmonary disease.,0.000000
1,1,46,normal,normal,Xray Chest PA and Lateral,"V76.12 SCREENING MAMMOGRAM XXXX,no hx ca or im...",NaN,None available.,No comparison chest x-XXXX. Well-expanded and ...,Normal_No_Finding,resized_images/row_1_frontal.jpg,resized_images/row_1_lateral.jpg,<findings> Heart size is upper limits of norma...,Heart size is upper limits of normal. Lungs ar...,No acute cardiopulmonary process.,0.333333
2,2,66,normal,normal,"Chest, 2 views; SPINE LUMBAR 3 VIEWS XXXX, XX...",Hematemesis; BACK PAIN 724.5,"XXXX, XXXX.",Chest. Both lungs are clear and expanded with ...,1. Chest. No active disease. 2. Lumbar spine n...,Normal_No_Finding,resized_images/row_2_frontal.jpg,resized_images/row_2_lateral.jpg,<findings> Chest. Both lungs are clear and exp...,Chest. Both lungs are clear and expanded with ...,1. Chest. No active disease. 2. Lumbar spine n...,1.000000
3,3,67,Lung/hypoinflation;Markings/bronchovascular,Lung;Markings,CHEST AP and lateral at XXXX XXXX/XXXX,"XXXX-year-old, MVA, chest pain",None.,There are low volumes with bronchovascular cro...,Low volumes with bronchovascular crowding. No ...,Non_Specific_Technical,resized_images/row_3_frontal.jpg,resized_images/row_3_lateral.jpg,<findings> Crowded lung XXXX bilaterally. Mini...,Crowded lung XXXX bilaterally. Minimal streaky...,1. Low lung volumes. 2. Minimal bibasilar opac...,0.325581
4,4,92,Markings/bronchovascular,Markings,Xray Chest PA and Lateral,"XXXX-year-old female, XXXX bleed",NaN,None available.,Heart size within normal limits. No focal alve...,Non_Specific_Technical,resized_images/row_4_frontal.jpg,resized_images/row_4_lateral.jpg,<findings> None available. </findings>\n<impre...,None available.,Heart size within normal limits. No focal alve...,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,193,3953,normal,normal,"PA and lateral chest x-XXXX dated XXXX, XXXX a...",XXXX-year-old XXXX with history of testicular ...,"Two-view chest radiograph dated XXXX, XXXX..","The lungs are clear bilaterally. Specifically,...",No acute cardiopulmonary abnormality.,Normal_No_Finding,resized_images/row_193_frontal.jpg,resized_images/row_193_lateral.jpg,<findings> There is hyperexpansion of the lung...,There is hyperexpansion of the lungs with flat...,1. No acute cardiopulmonary abnormality. 2. Em...,0.600000
194,194,3971,normal,normal,PA and lateral chest radiographs XXXX at XXXX ...,XXXX-year-old male with chest pain.,AP portable chest radiograph XXXX; PA and late...,The heart size and cardiomediastinal silhouett...,No acute cardiopulmonary finding.,Normal_No_Finding,resized_images/row_194_frontal.jpg,resized_images/row_194_lateral.jpg,<findings> None available. </findings>\n<impre...,None available.,No significant change from prior study. No acu...,0.190476
195,195,3974,Lung/hyperdistention;Pulmonary Emphysema;Airsp...,Lung;Pulmonary Emphysema;Airspace Disease;Spine,PA and lateral chest x-XXXX XXXX,XXXX,None available for review,The lungs are hyperexpanded consistent with em...,1. Hyperexpanded lungs suggesting emphysema. 2...,Alveolar_Opacities_Infections;Bones_Spine_Musc...,resized_images/row_195_frontal.jpg,resized_images/row_195_lateral.jpg,<findings> There are bilateral breast shadows....,There are bilateral breast shadows. The left b...,1. No acute cardiopulmonary abnormality. 2. Ri...,0.057143
196,196,3977,"Aorta, Thoracic/tortuous;Calcified Granuloma/l...","Aorta, Thoracic;Calcified Granuloma","PA and lateral chest x-XXXX XXXX, XXXX XXXX ho...","XXXX-year-old male, hypertension, chest pain","Chest x-XXXX XXXX, XXXX",Normal heart size. Stable unfolding the thorac...,No acute cardiopulmonary abnormality.,Nodules_Masses_Chronic_Fibrotic;Cardiomegaly_C...,resized_images/row_196_frontal.jpg,resized_images/row_196_lateral.jpg,<findings> There is a right-sided PICC with ti...,There is a right-sided PICC with tip at the ca...,1. Low volume study without acute cardiopulmon...,0.190476
197,197,3999,normal,normal,"CHEST PA and LATERAL: on XXXX, XXXX.",This is a XXXX-year-old female patient with sh...,"Chest x-XXXX, XXXX, XXXX.",None available.,The cardiac silhouette is normal in size and c...,Normal_No_Finding,resized_images/row_197_frontal.jpg,resized_images/row_197_lateral.jpg,<findings> No pneumothorax or pleural effusion...,No pneumothorax or pleural effusion present. N...,No acute cardiopulmonary abnormality identified.,0.133333